.default_template: &default_job_definition #la riutilizzerò dopo
  image: smclab/argocd-cli:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
    ARGOCD_SERVER: "argocd.openk9.io"
  before_script:
    - echo "ARGOCD_SERVER:$ARGOCD_SERVER"
    - echo "ARGOCD_APP_NAME:$ARGOCD_APP_NAME"
    - echo "ARGOCD_USERNAME:$ARGOCD_USERNAME"
    - argocd login "${ARGOCD_SERVER}" --username "${ARGOCD_USERNAME}" --password "${ARGOCD_PASSWORD}" --grpc-web

stages:
  - deploy

restart-tenant-manager:
  <<: *default_job_definition
  rules:
    - if: '$TRIGGER_JOB == "restart-tenant-manager"'
  script:
    - argocd app actions run k9-backend/tenant-manager restart --kind Deployment --namespace k9-backend --grpc-web

restart-datasource:
  <<: *default_job_definition
  rules:
    - if: '$TRIGGER_JOB == "restart-datasource"'
  script:
    - argocd app actions run k9-backend/datasource restart --kind Deployment --namespace k9-backend --grpc-web

restart-k8s-client:
  <<: *default_job_definition
  rules:
    - if: '$TRIGGER_JOB == "restart-k8s-client"'
  script:
    - argocd app actions run k9-backend/k8s-client restart --kind Deployment --namespace k9-backend --grpc-web
